### ISSUE TITLE
Can MinAtar experiments run on headless servers?

### ISSUE THREAD

**Issue by kaixin96** [ZhengyaoJiang/GTG#1]
Thanks for sharing the code for your excellent work!

I clone the repo and run `python torchbeast/monobeast.py --env=breakout --agent=GCN --xpid=T-1-1`. However, it throws an error message "ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running".

I am wondering if MinAtar experiments can run on headless servers. Can you help me? Many thanks!

**Comment by Spiph** [comment]
I am running into the same issue when running in a docker environment. I tried the solution from [this SO post](https://stackoverflow.com/questions/55811545/importerror-cannot-load-backend-tkagg-which-requires-the-tk-interactive-fra) but it looks like the code already implements the fix. Any help would be appreciated

**Comment by ZhengyaoJiang** [comment]
Hi, could you check whether this works now?

**Comment by Spiph** [comment]
After pulling in your changes, I am still seeing the same issue with TkAgg
